version: "3.8"

services:
  
  slave:
    image: vinsdocker/jmserver:latest    
    #container_name: jmeter-slave
    #script:
      # Generate random number from 1 to 10:
    #  - let MR_ID=$((1 + RANDOM % 10))
    depends_on:
      - master   

  master:
    image: vinsdocker/jmmaster:latest 
    container_name: jmeter-master
    ports:
      - "60000:60000"

